APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:qLQABdYPv3140nb0TusG9FSFu9P2+F321xD0Rmtok2g=
APP_DEBUG=true
APP_URL=http://localhost

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=paudterp_dbpaud
DB_USERNAME=paudterp_dbpaud
DB_PASSWORD=lf5HS)xO?w*w

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=teksin.cuch@gmail.com
MAIL_PASSWORD=ctxijetbxxxzugkj
MAIL_ENCRYPTION=tls 

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
